lane :test do
  # Create a Dummy File
  File.write("../my_demo_file.txt", "Some Content")

  # import/update this in cryptex
  cryptex(
    type: "import",
    in: "my_demo_file.txt",
    key: "some_key_my_file_can_be_found"
  )

  # export a file from cryptex
  cryptex(
    type: "export",
    out: "here_goes_my_file.txt",
    key: "some_key_my_file_can_be_found"
  )

  file_output = File.read("../here_goes_my_file.txt")
  puts "File Content: #{file_output.tr("\n", ' ')}"

  # delete the file
  cryptex(
    type: "delete",
    key: "some_key_my_file_can_be_found"
  )

  # Nuke's all files
  cryptex(
    type: "nuke"
  )
end
